import type { InsightCard, Order, Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "ram-001",
    name: "Frozen Chicken Samosa",
    category: "ramadan",
    price: 28,
    unit: "1kg pack",
    description: "Crispy frozen samosa triangles for quick iftar prep.",
    image_url:
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1200&q=80",
    certifications: ["Halal", "Frozen"],
    stock_level: 220,
    stock_status: "In Stock",
    ideal_for: "Arabic restaurants, cafeterias, cloud kitchens",
    dish_ideas: ["Chicken samosa", "Samosa chaat", "Iftar platter"],
  },
  {
    id: "ram-002",
    name: "Frozen Beef Kibbeh",
    category: "ramadan",
    price: 34,
    unit: "1kg pack",
    description: "Premium frozen kibbeh shells with seasoned beef filling.",
    image_url:
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    certifications: ["Halal", "Frozen"],
    stock_level: 180,
    stock_status: "In Stock",
    ideal_for: "Arabic grills, Levantine kitchens, catering",
    dish_ideas: ["Fried kibbeh", "Baked kibbeh", "Kibbeh with yogurt sauce"],
  },
  {
    id: "ram-003",
    name: "Kunafa Dough (Kataifi)",
    category: "ramadan",
    price: 22,
    unit: "500g pack",
    description: "Shredded kunafa pastry for dessert stations and bakery service.",
    image_url:
      "https://images.unsplash.com/photo-1551024709-8f23befc6cf7?auto=format&fit=crop&w=1200&q=80",
    certifications: ["Halal"],
    stock_level: 140,
    stock_status: "In Stock",
    ideal_for: "Dessert shops, Arabic restaurants, home bakers",
    dish_ideas: ["Kunafa naama", "Kunafa cups", "Kunafa rolls"],
  },
  {
    id: "ram-004",
    name: "Basmati Rice Premium",
    category: "ramadan",
    price: 48,
    unit: "5kg bag",
    description: "Long-grain basmati for biryani, mandi, and family meal packs.",
    image_url:
      "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80",
    certifications: ["Halal", "Premium Grade"],
    stock_level: 260,
    stock_status: "In Stock",
    ideal_for: "Biryani houses, mandi kitchens, bulk meal prep",
    dish_ideas: ["Chicken biryani", "Mandi rice", "Pilaf"],
  },
  {
    id: "ram-005",
    name: "Rooh Afza Concentrate",
    category: "ramadan",
    price: 19,
    unit: "800ml bottle",
    description: "Classic rose syrup concentrate for high-turn iftar beverages.",
    image_url:
      "https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&w=1200&q=80",
    certifications: ["Halal"],
    stock_level: 300,
    stock_status: "In Stock",
    ideal_for: "Iftar buffets, catering, beverage counters",
    dish_ideas: ["Rose milk", "Iftar cooler", "Falooda base"],
  },
  {
    id: "ram-006",
    name: "Premium Dates (Medjool)",
    category: "ramadan",
    price: 85,
    unit: "1kg box",
    description: "Jumbo medjool dates curated for iftar service and gifting.",
    image_url:
      "https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?auto=format&fit=crop&w=1200&q=80",
    certifications: ["Halal", "Premium Grade"],
    stock_level: 240,
    stock_status: "In Stock",
    ideal_for: "Hotels, Arabic restaurants, gifting desks",
    dish_ideas: ["Stuffed dates", "Date platter", "Date shake"],
  },
  {
    id: "ram-007",
    name: "Cooking Oil (Canola/Sunflower/Corn)",
    category: "ramadan",
    price: 44,
    unit: "5L can",
    description: "Multi-purpose blended cooking oil for high-volume kitchen use.",
    image_url:
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1200&q=80",
    certifications: ["Halal"],
    stock_level: 260,
    stock_status: "In Stock",
    ideal_for: "Cafeterias, catering kitchens, fry stations",
    dish_ideas: ["Fried samosa", "Spring rolls", "Pakora"],
  },
  {
    id: "ram-008",
    name: "Extra Virgin Olive Oil",
    category: "ramadan",
    price: 39,
    unit: "1L bottle",
    description: "Premium olive oil for marinades, dressings, and finishing.",
    image_url:
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1200&q=80",
    certifications: ["Halal", "Premium Grade"],
    stock_level: 150,
    stock_status: "In Stock",
    ideal_for: "Arabic grills, healthy kitchens, premium catering",
    dish_ideas: ["Fatoush dressing", "Grilled chicken marinade", "Hummus drizzle"],
  },
];

export const mockOrders: Order[] = [
  {
    id: "d67fbfc2-f4c9-4565-a4d8-cd977a4f89ce",
    order_number: "RAM-2026-0147",
    user_id: "demo-customer-001",
    status: "confirmed",
    delivery_date: "2026-02-27",
    total_amount: 1248,
    deposit_amount: 1248,
    deposit_paid: true,
    items: [
      {
        product_id: "ram-001",
        name: "Frozen Chicken Samosa",
        qty: 12,
        unit_price: 28,
      },
      {
        product_id: "ram-002",
        name: "Frozen Beef Kibbeh",
        qty: 10,
        unit_price: 34,
      },
      {
        product_id: "ram-006",
        name: "Premium Dates (Medjool)",
        qty: 6,
        unit_price: 85,
      },
    ],
  },
];

export const mockInsights: InsightCard[] = [];
